---
- name: Create SQS queue Using Ansible
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Create SQS Queue
      sqs_queue:
        name: nithya_sqs
        region: region1
        queue_type: type1
        content_based_deduplication: true
        default_visibility_timeout: dvt
        message_retention_period: mrp
        maximum_message_size: mms
        delivery_delay: dd
        receive_message_wait_time: rmwt
        
    - name: Create alarm SNS Topic 
      community.aws.sns_topic:
        name: snsalarm
        state: present
        region: us-west-2
        subscriptions:
          - endpoint: "endpoint1"
            protocol: "protocol1"
          

