---
- name: Create SQS queue Using Ansible
  hosts: localhost
  gather_facts: False

  tasks:
     -name: task #1 Create Queue
     SQS_queue:
         name: "SQSQueue"
         region: region1
         default_visibility_timeout: dvt
         message_retention_period: mtp
         maximum_message_size: mms
         delivery_delay: dd
         receive_message_wait_time: rmwt

